# Generated by Django 3.1.1 on 2021-02-03 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anio_lectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_lectivo', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['anio_lectivo'],
            },
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(max_length=100)),
                ('ciclo_corto', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['ciclo'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=45)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.ciclo')),
            ],
            options={
                'ordering': ['curso'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('departamento_corto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['departamento'],
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_acceso', models.CharField(max_length=45)),
                ('estado', models.IntegerField()),
                ('anio_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.anio_lectivo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.curso')),
            ],
            options={
                'ordering': ['clave_acceso'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluacion', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['evaluacion'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=100)),
                ('nombre_corto', models.CharField(max_length=10)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.ciclo')),
            ],
            options={
                'ordering': ['modulo'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['rol'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Pregunta_Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pregunta_encuesta', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['tipo_pregunta_encuesta'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.departamento')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Usuario_modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.anio_lectivo')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.modulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.usuario')),
            ],
            options={
                'ordering': ['usuario'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta_encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuesta')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta_Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_encuesta', models.CharField(max_length=100)),
                ('tipo_pregunta_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.tipo_pregunta_encuesta')),
            ],
            options={
                'ordering': ['pregunta_encuesta'],
            },
        ),
        migrations.CreateModel(
            name='Opcion_Pregunta_Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion_pregunta_encuesta', models.CharField(max_length=100)),
                ('pregunta_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.pregunta')),
            ],
            options={
                'ordering': ['opcion_pregunta_encuesta'],
            },
        ),
        migrations.AddField(
            model_name='encuesta',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.evaluacion'),
        ),
        migrations.CreateModel(
            name='Detalle_respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('pregunta_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.pregunta_encuesta')),
                ('respuesta_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.respuesta_encuesta')),
                ('usuario_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.usuario_modulo')),
            ],
            options={
                'ordering': ['valor'],
            },
        ),
    ]
