# Generated by Django 3.1.1 on 2021-03-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_auto_20210203_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta_Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_acceso', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['clave_acceso'],
            },
        ),
    ]
